"""Core functionality for khazaddum"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['CHACHE_DIR', 'QueryResult', 'DatabaseAgent']

# %% ../nbs/00_core.ipynb 3
from pydantic import BaseModel
from typing import Optional

class QueryResult(BaseModel):
    query: str
    success: bool
    data: Optional[list[dict]] = None
    error: Optional[str] = None
    row_count: int = 0
    execution_time: float = 0.0

# %% ../nbs/00_core.ipynb 5
from abc import ABC, abstractmethod

class DatabaseAgent(ABC):
    """Base class for database-specific agents"""
    
    @property
    @abstractmethod
    def dialect_name(self) -> str:
        """Return the database dialect name (e.g., 'snowflake', 'oracle', 'kibana')"""
        pass
    
    @abstractmethod
    def connect(self):
        """Establish connection to the database"""
        pass
    
    @property
    @abstractmethod
    def check_connection(self) -> bool:
        """Check if connection is active"""
        pass
    
    @abstractmethod
    def execute_query(
        self, 
        **kwargs
    ) -> QueryResult:
        """Execute a safe SELECT query and return structured results"""
        pass
    
    

# %% ../nbs/00_core.ipynb 6
from fastcore.all import *
import json
CHACHE_DIR = Path('../cache')
CHACHE_DIR.mkdir(exist_ok=True)
